site_name: Awesome Space Security
site_url: https://awesome-space-security.peco602.com
site_description: A curated list of awesome resources about the security of space systems.
site_author: Giovanni Pecoraro
repo_name: peco602/awesome-space-security
repo_url: https://github.com/peco602/awesome-space-security
theme:
  name: material
  palette:
    primary: blue
    accent: pink
extra:
  social:
    - icon: fontawesome/solid/blog
      link: https://www.peco602.com
    - icon: fontawesome/brands/github
      link: https://github.com/peco602
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peco602
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/giovanni-pecoraro-078500155/
    - icon: fontawesome/solid/envelope
      link: mailto:giovanni1.pecoraro@protonmail.com
  analytics:
    provider: google
    property: G-YPP6CHKDDE
extra_css:
    - css/extra.css
nav:
  - "Failure Is Not An Option": "index.md"
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      preserve_tabs: true
